basePath: /
consumes:
- application/json
definitions:
  URLDTO:
    properties:
      url:
        type: string
        x-go-name: URL
    type: object
    x-go-package: github.com/ms-url-shortner/app/model
host: localhost:4232
info:
  description: Documentation of our awesome API.
  title: awesome.
  version: 1.0.0
paths:
  /ms-url-shortner/getshorturl:
    post:
      description: return the short url
      operationId: getShortURL
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/URLDTO'
      - in: header
        name: Authorization
        type: string
      responses:
        "200":
          $ref: '#/responses/shortURLResponse'
      tags:
      - shortURL
  /ms-url-shortner/ping:
    get:
      description: return the ping from application
      operationId: getPing
      parameters:
      - in: path
        name: user_id
        required: true
        type: string
        x-go-name: UserID
      responses:
        "200":
          $ref: '#/responses/Success'
      tags:
      - ping
produces:
- application/json
responses:
  Success:
    description: ""
  shortURLResponse:
    description: ""
    schema:
      $ref: '#/definitions/URLDTO'
schemes:
- http
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
