apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-urlshortner
  labels:
    {{- include "url-shortner-charts.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "url-shortner-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "url-shortner-charts.selectorLabels" . | nindent 8 }}
      annotations:
        # these annotation are not mandatory while using service monitor, but it is good practice to do it
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "4242"  
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
            - containerPort: {{ .Values.service.port }}
              name: metrics