apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-urlshortnersvc
  labels:
    {{- include "url-shortner-charts.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: 30054
  selector:
    {{- include "url-shortner-charts.selectorLabels" . | nindent 4 }}
