{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "url-shortner-charts.selectorLabels" . | nindent 6 }}
  endpoints:
  # we don't need to define path as default path is /metrics
  - targetPort: {{ .Values.service.port }}
{{- end -}}